name: Convert lessons

on:
  push:
    paths:
      # Запускаться, когда что-то меняется в этой папке
      - 'lessons/source/**'

permissions:
  contents: write # Даем права на запись (чтобы коммитить .md файлы)

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Используем Node 18

      - name: Install dependencies
        # Используем npm install, чтобы он установил новые библиотеки (mammoth)
        run: npm install

      - name: Run lesson generator script
        run: npm run generate-lessons

      - name: Commit generated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/lessons/*.md public/lessons/*/*.md public/lessons/*/images/* public/lessons/index.json README.md
          # Проверяем, есть ли изменения, перед коммитом
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto: Generated lessons from source files"
            git push
          else
            echo "No changes to commit."
          fi
